export type SettingField = {
    type: "image" | "text" | "textarea";
    keyName: string;
    title: string;
    description?: string;
    placeholder?: string;
    rows?: number;
};

export type SettingSection = {
    title: string;
    description?: string;
    fields: SettingField[];
};

export const siteSettingsSections: SettingSection[] = [
    {
        title: "Контакти та навігація",
        description: "Глобальні контакти, які використовуються у футері та на сторінці контактів.",
        fields: [
            { type: "text", keyName: "header_topbar_text", title: "Верхній рядок шапки" },
            { type: "text", keyName: "contact_email", title: "Email" },
            { type: "text", keyName: "contact_phone", title: "Телефон" },
            { type: "text", keyName: "contact_address", title: "Адреса" },
            { type: "text", keyName: "contact_hours", title: "Графік роботи" },
            { type: "text", keyName: "contact_map_url", title: "Посилання на мапу" },
        ],
    },
    {
        title: "Hero B2B-порталу",
        description: "Головний екран сайту.",
        fields: [
            { type: "image", keyName: "hero_image", title: "Hero фото" },
            { type: "text", keyName: "hero_badge", title: "Badge" },
            { type: "text", keyName: "hero_title_line_1", title: "Заголовок, рядок 1" },
            { type: "text", keyName: "hero_title_line_2", title: "Заголовок, рядок 2" },
            { type: "textarea", keyName: "hero_description", title: "Опис", rows: 3 },
            { type: "text", keyName: "hero_primary_button_text", title: "Кнопка 1: текст" },
            { type: "text", keyName: "hero_primary_button_link", title: "Кнопка 1: посилання" },
            { type: "text", keyName: "hero_secondary_button_text", title: "Кнопка 2: текст" },
            { type: "text", keyName: "hero_secondary_button_link", title: "Кнопка 2: посилання" },
            { type: "text", keyName: "hero_metric_1_value", title: "Метрика 1: значення" },
            { type: "text", keyName: "hero_metric_1_label", title: "Метрика 1: підпис" },
            { type: "text", keyName: "hero_metric_2_value", title: "Метрика 2: значення" },
            { type: "text", keyName: "hero_metric_2_label", title: "Метрика 2: підпис" },
            { type: "text", keyName: "hero_metric_3_value", title: "Метрика 3: значення" },
            { type: "text", keyName: "hero_metric_3_label", title: "Метрика 3: підпис" },
            { type: "textarea", keyName: "hero_partner_badge", title: "Права картка: badge", rows: 2 },
            { type: "textarea", keyName: "hero_partner_text", title: "Права картка: короткий текст", rows: 3 },
            { type: "text", keyName: "hero_partner_label_1", title: "Таблиця справа: лейбл 1" },
            { type: "text", keyName: "hero_partner_value_1", title: "Таблиця справа: значення 1" },
            { type: "text", keyName: "hero_partner_label_2", title: "Таблиця справа: лейбл 2" },
            { type: "text", keyName: "hero_partner_value_2", title: "Таблиця справа: значення 2" },
            { type: "text", keyName: "hero_partner_label_3", title: "Таблиця справа: лейбл 3" },
            { type: "text", keyName: "hero_partner_value_3", title: "Таблиця справа: значення 3" },
            { type: "text", keyName: "hero_process_badge", title: "Світла картка: badge" },
            { type: "text", keyName: "hero_process_title_line_1", title: "Світла картка: заголовок 1" },
            { type: "text", keyName: "hero_process_title_line_2", title: "Світла картка: заголовок 2" },
            { type: "textarea", keyName: "hero_process_description", title: "Світла картка: опис", rows: 3 },
            {
                type: "textarea",
                keyName: "hero_badges_list",
                title: "Плашки під метриками",
                description: "Один рядок = одна плашка",
                rows: 4,
            },
            {
                type: "textarea",
                keyName: "hero_capability_list",
                title: "Рухомий рядок",
                description: "Один рядок = один елемент",
                rows: 6,
            },
            {
                type: "textarea",
                keyName: "hero_side_notes",
                title: "Нотатки зліва на desktop",
                description: "Один рядок = один елемент",
                rows: 4,
            },
        ],
    },
    {
        title: "Категорії та каталоги",
        description: "Заголовки, картки категорій і мета-тексти сторінок каталогу.",
        fields: [
            { type: "text", keyName: "categories_title_line_1", title: "Заголовок 1" },
            { type: "text", keyName: "categories_title_line_2", title: "Заголовок 2 / акцент" },
            { type: "text", keyName: "categories_caption", title: "Підпис праворуч" },
            { type: "text", keyName: "categories_stat_1_value", title: "Стат 1: значення" },
            { type: "text", keyName: "categories_stat_1_label", title: "Стат 1: підпис" },
            { type: "text", keyName: "categories_stat_2_value", title: "Стат 2: значення" },
            { type: "text", keyName: "categories_stat_2_label", title: "Стат 2: підпис" },
            { type: "text", keyName: "categories_stat_3_value", title: "Стат 3: значення" },
            { type: "text", keyName: "categories_stat_3_label", title: "Стат 3: підпис" },
            { type: "text", keyName: "category_women_title", title: "Жіноче: заголовок" },
            { type: "text", keyName: "category_women_short_label", title: "Жіноче: коротка назва" },
            { type: "text", keyName: "category_women_tag", title: "Жіноче: badge" },
            { type: "textarea", keyName: "category_women_desc", title: "Жіноче: опис", rows: 2 },
            { type: "image", keyName: "category_women_image", title: "Жіноче: фото" },
            { type: "text", keyName: "category_women_link", title: "Жіноче: посилання" },
            { type: "text", keyName: "category_men_title", title: "Чоловіче: заголовок" },
            { type: "text", keyName: "category_men_short_label", title: "Чоловіче: коротка назва" },
            { type: "text", keyName: "category_men_tag", title: "Чоловіче: badge" },
            { type: "textarea", keyName: "category_men_desc", title: "Чоловіче: опис", rows: 2 },
            { type: "image", keyName: "category_men_image", title: "Чоловіче: фото" },
            { type: "text", keyName: "category_men_link", title: "Чоловіче: посилання" },
            { type: "text", keyName: "category_kids_title", title: "Дитяче: заголовок" },
            { type: "text", keyName: "category_kids_short_label", title: "Дитяче: коротка назва" },
            { type: "text", keyName: "category_kids_tag", title: "Дитяче: badge" },
            { type: "textarea", keyName: "category_kids_desc", title: "Дитяче: опис", rows: 2 },
            { type: "image", keyName: "category_kids_image", title: "Дитяче: фото" },
            { type: "text", keyName: "category_kids_link", title: "Дитяче: посилання" },
            { type: "text", keyName: "category_work_title", title: "Робоче: заголовок" },
            { type: "text", keyName: "category_work_short_label", title: "Робоче: коротка назва" },
            { type: "text", keyName: "category_work_tag", title: "Робоче: badge" },
            { type: "textarea", keyName: "category_work_desc", title: "Робоче: опис", rows: 2 },
            { type: "image", keyName: "category_work_image", title: "Робоче: фото" },
            { type: "text", keyName: "category_work_link", title: "Робоче: посилання" },
            { type: "text", keyName: "category_accessories_title", title: "Аксесуари: заголовок" },
            { type: "text", keyName: "category_accessories_short_label", title: "Аксесуари: коротка назва" },
            { type: "text", keyName: "category_accessories_tag", title: "Аксесуари: badge" },
            { type: "textarea", keyName: "category_accessories_desc", title: "Аксесуари: опис", rows: 2 },
            { type: "image", keyName: "category_accessories_image", title: "Аксесуари: фото" },
            { type: "text", keyName: "category_accessories_link", title: "Аксесуари: посилання" },
            { type: "text", keyName: "category_sale_title", title: "Sale: заголовок" },
            { type: "text", keyName: "category_sale_short_label", title: "Sale: коротка назва" },
            { type: "text", keyName: "category_sale_tag", title: "Sale: badge" },
            { type: "textarea", keyName: "category_sale_desc", title: "Sale: опис", rows: 2 },
            { type: "image", keyName: "category_sale_image", title: "Sale: фото" },
            { type: "text", keyName: "category_sale_link", title: "Sale: посилання" },
            { type: "text", keyName: "catalog_women_title", title: "Каталог women: title" },
            { type: "textarea", keyName: "catalog_women_subtitle", title: "Каталог women: subtitle", rows: 2 },
            { type: "textarea", keyName: "catalog_women_tagline", title: "Каталог women: tagline", rows: 2 },
            { type: "text", keyName: "catalog_women_cta", title: "Каталог women: CTA" },
            { type: "text", keyName: "catalog_men_title", title: "Каталог men: title" },
            { type: "textarea", keyName: "catalog_men_subtitle", title: "Каталог men: subtitle", rows: 2 },
            { type: "textarea", keyName: "catalog_men_tagline", title: "Каталог men: tagline", rows: 2 },
            { type: "text", keyName: "catalog_men_cta", title: "Каталог men: CTA" },
            { type: "text", keyName: "catalog_kids_title", title: "Каталог kids: title" },
            { type: "textarea", keyName: "catalog_kids_subtitle", title: "Каталог kids: subtitle", rows: 2 },
            { type: "textarea", keyName: "catalog_kids_tagline", title: "Каталог kids: tagline", rows: 2 },
            { type: "text", keyName: "catalog_kids_cta", title: "Каталог kids: CTA" },
            { type: "text", keyName: "catalog_work_title", title: "Каталог work: title" },
            { type: "textarea", keyName: "catalog_work_subtitle", title: "Каталог work: subtitle", rows: 2 },
            { type: "textarea", keyName: "catalog_work_tagline", title: "Каталог work: tagline", rows: 2 },
            { type: "text", keyName: "catalog_work_cta", title: "Каталог work: CTA" },
            { type: "text", keyName: "catalog_accessories_title", title: "Каталог accessories: title" },
            { type: "textarea", keyName: "catalog_accessories_subtitle", title: "Каталог accessories: subtitle", rows: 2 },
            { type: "textarea", keyName: "catalog_accessories_tagline", title: "Каталог accessories: tagline", rows: 2 },
            { type: "text", keyName: "catalog_accessories_cta", title: "Каталог accessories: CTA" },
            { type: "text", keyName: "catalog_sale_title", title: "Каталог sale: title" },
            { type: "textarea", keyName: "catalog_sale_subtitle", title: "Каталог sale: subtitle", rows: 2 },
            { type: "textarea", keyName: "catalog_sale_tagline", title: "Каталог sale: tagline", rows: 2 },
            { type: "text", keyName: "catalog_sale_cta", title: "Каталог sale: CTA" },
        ],
    },
    {
        title: "Популярні товари",
        description: "Заголовок секції з топовими моделями на головній.",
        fields: [
            { type: "text", keyName: "bestsellers_badge", title: "Badge" },
            { type: "text", keyName: "bestsellers_title", title: "Заголовок" },
            { type: "text", keyName: "bestsellers_title_accent", title: "Акцент заголовка" },
            { type: "text", keyName: "bestsellers_stat_1_value", title: "Стат 1: значення" },
            { type: "text", keyName: "bestsellers_stat_1_label", title: "Стат 1: підпис" },
            { type: "text", keyName: "bestsellers_stat_2_value", title: "Стат 2: значення" },
            { type: "text", keyName: "bestsellers_stat_2_label", title: "Стат 2: підпис" },
            { type: "text", keyName: "bestsellers_stat_3_value", title: "Стат 3: значення" },
            { type: "text", keyName: "bestsellers_stat_3_label", title: "Стат 3: підпис" },
        ],
    },
    {
        title: "Блок співпраці",
        description: "Секція \"Як почати співпрацю\" на головній.",
        fields: [
            { type: "text", keyName: "collab_badge", title: "Badge" },
            { type: "text", keyName: "collab_title_line_1", title: "Заголовок 1" },
            { type: "text", keyName: "collab_title_line_2", title: "Заголовок 2" },
            { type: "textarea", keyName: "collab_description", title: "Опис", rows: 3 },
            { type: "text", keyName: "collab_button_text", title: "Кнопка: текст" },
            { type: "text", keyName: "collab_button_link", title: "Кнопка: посилання" },
            { type: "image", keyName: "collab_image", title: "Головне фото" },
            { type: "text", keyName: "collab_card_1_badge", title: "Темна картка: badge" },
            { type: "textarea", keyName: "collab_card_1_title", title: "Темна картка: текст", rows: 3 },
            { type: "text", keyName: "collab_card_2_badge", title: "Світла картка: badge" },
            { type: "textarea", keyName: "collab_card_2_text", title: "Світла картка: текст", rows: 3 },
            {
                type: "textarea",
                keyName: "collab_tags",
                title: "Теги",
                description: "Один рядок = один тег",
                rows: 5,
            },
            {
                type: "textarea",
                keyName: "collab_steps",
                title: "Кроки",
                description: "Один рядок = один крок",
                rows: 5,
            },
        ],
    },
    {
        title: "Чому обирають нас",
        description: "Секція переваг на головній.",
        fields: [
            { type: "text", keyName: "whychoose_badge", title: "Badge" },
            { type: "text", keyName: "whychoose_title", title: "Заголовок" },
            { type: "text", keyName: "whychoose_title_outline", title: "Акцент заголовка" },
            { type: "text", keyName: "whychoose_stat_1_value", title: "Стат 1: значення" },
            { type: "text", keyName: "whychoose_stat_1_label", title: "Стат 1: підпис" },
            { type: "text", keyName: "whychoose_stat_2_value", title: "Стат 2: значення" },
            { type: "text", keyName: "whychoose_stat_2_label", title: "Стат 2: підпис" },
            { type: "text", keyName: "whychoose_stat_3_value", title: "Стат 3: значення" },
            { type: "text", keyName: "whychoose_stat_3_label", title: "Стат 3: підпис" },
            { type: "text", keyName: "whychoose_card_1_title", title: "Картка 1: заголовок" },
            { type: "textarea", keyName: "whychoose_card_1_desc", title: "Картка 1: опис", rows: 3 },
            { type: "text", keyName: "whychoose_card_2_title", title: "Картка 2: заголовок" },
            { type: "textarea", keyName: "whychoose_card_2_desc", title: "Картка 2: опис", rows: 3 },
            { type: "text", keyName: "whychoose_card_3_title", title: "Картка 3: заголовок" },
            { type: "textarea", keyName: "whychoose_card_3_desc", title: "Картка 3: опис", rows: 3 },
        ],
    },
    {
        title: "Відгуки та розсилка",
        description: "Відгуки, trust-метрики та блок email-розсилки.",
        fields: [
            { type: "text", keyName: "reviews_badge", title: "Відгуки: badge" },
            { type: "text", keyName: "reviews_title", title: "Відгуки: заголовок" },
            { type: "text", keyName: "reviews_title_accent", title: "Відгуки: акцент" },
            { type: "text", keyName: "reviews_stat_1_value", title: "Відгуки: стат 1 значення" },
            { type: "text", keyName: "reviews_stat_1_label", title: "Відгуки: стат 1 підпис" },
            { type: "text", keyName: "reviews_stat_2_value", title: "Відгуки: стат 2 значення" },
            { type: "text", keyName: "reviews_stat_2_label", title: "Відгуки: стат 2 підпис" },
            { type: "textarea", keyName: "review_1_text", title: "Відгук 1: текст", rows: 4 },
            { type: "text", keyName: "review_1_author", title: "Відгук 1: автор" },
            { type: "textarea", keyName: "review_2_text", title: "Відгук 2: текст", rows: 4 },
            { type: "text", keyName: "review_2_author", title: "Відгук 2: автор" },
            { type: "text", keyName: "subscribe_badge", title: "Розсилка: badge" },
            { type: "text", keyName: "subscribe_title", title: "Розсилка: заголовок" },
            { type: "textarea", keyName: "subscribe_description", title: "Розсилка: опис", rows: 3 },
            { type: "text", keyName: "subscribe_button_text", title: "Розсилка: текст кнопки" },
            { type: "text", keyName: "subscribe_note", title: "Розсилка: примітка" },
        ],
    },
    {
        title: "Wholesale: головний блок",
        description: "Перший екран сторінки умов співпраці.",
        fields: [
            { type: "text", keyName: "wholesale_page_title", title: "Сторінка: title" },
            { type: "textarea", keyName: "wholesale_page_subtitle", title: "Сторінка: subtitle", rows: 2 },
            { type: "text", keyName: "wholesale_hero_badge", title: "Hero: badge" },
            { type: "text", keyName: "wholesale_hero_title_line_1", title: "Hero: заголовок 1" },
            { type: "text", keyName: "wholesale_hero_title_line_2", title: "Hero: заголовок 2" },
            { type: "text", keyName: "wholesale_hero_title_line_3", title: "Hero: заголовок 3" },
            { type: "textarea", keyName: "wholesale_hero_description", title: "Hero: опис", rows: 3 },
            { type: "text", keyName: "wholesale_hero_primary_button_text", title: "Hero: кнопка 1 текст" },
            { type: "text", keyName: "wholesale_hero_primary_button_link", title: "Hero: кнопка 1 посилання" },
            { type: "text", keyName: "wholesale_hero_secondary_button_text", title: "Hero: кнопка 2 текст" },
            { type: "text", keyName: "wholesale_hero_secondary_button_link", title: "Hero: кнопка 2 посилання" },
            { type: "text", keyName: "wholesale_hero_metric_1_value", title: "Hero: метрика 1 значення" },
            { type: "text", keyName: "wholesale_hero_metric_1_label", title: "Hero: метрика 1 підпис" },
            { type: "text", keyName: "wholesale_hero_metric_2_value", title: "Hero: метрика 2 значення" },
            { type: "text", keyName: "wholesale_hero_metric_2_label", title: "Hero: метрика 2 підпис" },
            { type: "text", keyName: "wholesale_hero_metric_3_value", title: "Hero: метрика 3 значення" },
            { type: "text", keyName: "wholesale_hero_metric_3_label", title: "Hero: метрика 3 підпис" },
        ],
    },
    {
        title: "Wholesale: переваги та приклад",
        description: "Блоки переваг і таблиця прикладу замовлення.",
        fields: [
            { type: "text", keyName: "wholesale_benefits_badge", title: "Переваги: badge" },
            { type: "text", keyName: "wholesale_benefits_title", title: "Переваги: заголовок" },
            { type: "text", keyName: "wholesale_benefits_title_accent", title: "Переваги: акцент" },
            { type: "text", keyName: "wholesale_benefits_meta_1_value", title: "Переваги: мета 1 значення" },
            { type: "text", keyName: "wholesale_benefits_meta_1_label", title: "Переваги: мета 1 підпис" },
            { type: "text", keyName: "wholesale_benefits_meta_2_value", title: "Переваги: мета 2 значення" },
            { type: "text", keyName: "wholesale_benefits_meta_2_label", title: "Переваги: мета 2 підпис" },
            { type: "text", keyName: "wholesale_benefits_meta_3_value", title: "Переваги: мета 3 значення" },
            { type: "text", keyName: "wholesale_benefits_meta_3_label", title: "Переваги: мета 3 підпис" },
            { type: "text", keyName: "wholesale_benefit_1_title", title: "Перевага 1: заголовок" },
            { type: "textarea", keyName: "wholesale_benefit_1_desc", title: "Перевага 1: опис", rows: 3 },
            { type: "text", keyName: "wholesale_benefit_2_title", title: "Перевага 2: заголовок" },
            { type: "textarea", keyName: "wholesale_benefit_2_desc", title: "Перевага 2: опис", rows: 3 },
            { type: "text", keyName: "wholesale_benefit_3_title", title: "Перевага 3: заголовок" },
            { type: "textarea", keyName: "wholesale_benefit_3_desc", title: "Перевага 3: опис", rows: 3 },
            { type: "text", keyName: "wholesale_matrix_title", title: "Матриця: заголовок" },
            { type: "text", keyName: "wholesale_matrix_title_accent", title: "Матриця: акцент" },
            { type: "textarea", keyName: "wholesale_matrix_description", title: "Матриця: опис", rows: 3 },
            { type: "text", keyName: "wholesale_matrix_cta_text", title: "Матриця: кнопка текст" },
            { type: "text", keyName: "wholesale_matrix_cta_link", title: "Матриця: кнопка посилання" },
            { type: "text", keyName: "wholesale_matrix_meta_1_value", title: "Матриця: мета 1 значення" },
            { type: "text", keyName: "wholesale_matrix_meta_1_label", title: "Матриця: мета 1 підпис" },
            { type: "text", keyName: "wholesale_matrix_meta_2_value", title: "Матриця: мета 2 значення" },
            { type: "text", keyName: "wholesale_matrix_meta_2_label", title: "Матриця: мета 2 підпис" },
            { type: "text", keyName: "wholesale_matrix_meta_3_value", title: "Матриця: мета 3 значення" },
            { type: "text", keyName: "wholesale_matrix_meta_3_label", title: "Матриця: мета 3 підпис" },
        ],
    },
    {
        title: "Wholesale: форма запиту",
        description: "Ліва частина блоку та тексти у формі.",
        fields: [
            { type: "text", keyName: "wholesale_form_badge", title: "Ліва колонка: badge" },
            { type: "text", keyName: "wholesale_form_title", title: "Ліва колонка: заголовок" },
            { type: "text", keyName: "wholesale_form_title_accent", title: "Ліва колонка: акцент" },
            { type: "textarea", keyName: "wholesale_form_description", title: "Ліва колонка: опис", rows: 3 },
            { type: "text", keyName: "wholesale_form_highlight_1", title: "Перевага 1" },
            { type: "text", keyName: "wholesale_form_highlight_2", title: "Перевага 2" },
            { type: "text", keyName: "wholesale_form_highlight_3", title: "Перевага 3" },
            { type: "text", keyName: "wholesale_form_panel_badge", title: "Форма: badge" },
            { type: "text", keyName: "wholesale_form_label_company", title: "Форма: компанія / ФОП" },
            { type: "text", keyName: "wholesale_form_label_contact", title: "Форма: контактна особа" },
            { type: "text", keyName: "wholesale_form_label_phone", title: "Форма: телефон" },
            { type: "text", keyName: "wholesale_form_label_email", title: "Форма: email" },
            { type: "text", keyName: "wholesale_form_label_format", title: "Форма: формат продажу" },
            { type: "text", keyName: "wholesale_form_label_interest", title: "Форма: що цікавить" },
            { type: "text", keyName: "wholesale_form_placeholder_phone", title: "Форма: плейсхолдер телефону" },
            { type: "textarea", keyName: "wholesale_form_placeholder_interest", title: "Форма: плейсхолдер запиту", rows: 3 },
            { type: "textarea", keyName: "wholesale_form_format_options", title: "Форма: варіанти select", description: "Один рядок = одна опція", rows: 4 },
            { type: "text", keyName: "wholesale_form_submit_text", title: "Форма: текст кнопки" },
        ],
    },
    {
        title: "Footer",
        description: "Нижня частина сайту.",
        fields: [
            { type: "text", keyName: "footer_brand_subtitle", title: "Підпис під логотипом" },
            { type: "textarea", keyName: "footer_description", title: "Опис", rows: 3 },
            { type: "textarea", keyName: "footer_tags", title: "Теги", description: "Один рядок = один тег", rows: 4 },
            { type: "text", keyName: "footer_primary_button_text", title: "Кнопка 1: текст" },
            { type: "text", keyName: "footer_primary_button_link", title: "Кнопка 1: посилання" },
            { type: "text", keyName: "footer_secondary_button_text", title: "Кнопка 2: текст" },
            { type: "text", keyName: "footer_secondary_button_link", title: "Кнопка 2: посилання" },
            { type: "text", keyName: "footer_support_title", title: "Заголовок підтримки" },
            { type: "text", keyName: "footer_phone_label", title: "Лейбл телефону" },
            { type: "text", keyName: "footer_email_label", title: "Лейбл email" },
            { type: "text", keyName: "footer_address_label", title: "Лейбл адреси" },
            { type: "text", keyName: "footer_hours_title", title: "Лейбл графіку" },
            { type: "textarea", keyName: "footer_hours_text", title: "Текст графіку", rows: 3 },
            { type: "text", keyName: "footer_legal_text", title: "Копірайт" },
        ],
    },
    {
        title: "Сторінка: Про нас",
        description: "Тексти сторінки About.",
        fields: [
            { type: "text", keyName: "about_page_title", title: "Title" },
            { type: "textarea", keyName: "about_page_subtitle", title: "Subtitle", rows: 2 },
            { type: "textarea", keyName: "about_intro_1", title: "Вступ 1", rows: 3 },
            { type: "textarea", keyName: "about_intro_2", title: "Вступ 2", rows: 3 },
            { type: "text", keyName: "about_principles_title", title: "Заголовок блоку принципів" },
            { type: "text", keyName: "about_principle_1_title", title: "Принцип 1: заголовок" },
            { type: "textarea", keyName: "about_principle_1_text", title: "Принцип 1: текст", rows: 3 },
            { type: "text", keyName: "about_principle_2_title", title: "Принцип 2: заголовок" },
            { type: "textarea", keyName: "about_principle_2_text", title: "Принцип 2: текст", rows: 3 },
            { type: "text", keyName: "about_principle_3_title", title: "Принцип 3: заголовок" },
            { type: "textarea", keyName: "about_principle_3_text", title: "Принцип 3: текст", rows: 3 },
            { type: "text", keyName: "about_audience_title", title: "Кому підходимо: заголовок" },
            { type: "textarea", keyName: "about_audience_text", title: "Кому підходимо: текст", rows: 3 },
            { type: "text", keyName: "about_benefits_title", title: "Що ви отримуєте: заголовок" },
            { type: "textarea", keyName: "about_benefits_list", title: "Що ви отримуєте: список", description: "Один рядок = один пункт", rows: 6 },
        ],
    },
    {
        title: "Сторінка: Контакти",
        description: "Тексти та підказки сторінки Contact.",
        fields: [
            { type: "text", keyName: "contact_page_title", title: "Title" },
            { type: "textarea", keyName: "contact_page_subtitle", title: "Subtitle", rows: 2 },
            { type: "textarea", keyName: "contact_page_intro", title: "Вступ", rows: 3 },
            { type: "text", keyName: "contact_email_card_title", title: "Картка email: заголовок" },
            { type: "textarea", keyName: "contact_email_card_note", title: "Картка email: примітка", rows: 2 },
            { type: "text", keyName: "contact_phone_card_title", title: "Картка телефону: заголовок" },
            { type: "textarea", keyName: "contact_phone_card_note", title: "Картка телефону: примітка", rows: 2 },
            { type: "text", keyName: "contact_address_card_title", title: "Картка адреси: заголовок" },
            { type: "textarea", keyName: "contact_address_card_note", title: "Картка адреси: примітка", rows: 2 },
            { type: "text", keyName: "contact_help_title", title: "Чим можемо допомогти: заголовок" },
            { type: "textarea", keyName: "contact_help_list", title: "Чим можемо допомогти: список", description: "Один рядок = один пункт", rows: 5 },
            { type: "text", keyName: "contact_response_title", title: "Режим відповіді: заголовок" },
            { type: "textarea", keyName: "contact_response_text", title: "Режим відповіді: текст", rows: 3 },
            { type: "text", keyName: "contact_response_direct_label", title: "Підпис прямого контакту" },
        ],
    },
    {
        title: "Сторінка: Логістика",
        description: "Блоки сторінки B2B правил та логістики.",
        fields: [
            { type: "text", keyName: "delivery_page_title", title: "Title" },
            { type: "textarea", keyName: "delivery_page_subtitle", title: "Subtitle", rows: 2 },
            { type: "text", keyName: "delivery_banner_title", title: "Банер: заголовок" },
            { type: "textarea", keyName: "delivery_banner_subtitle", title: "Банер: підзаголовок", rows: 2 },
            { type: "text", keyName: "delivery_card_1_badge", title: "Картка 1: badge" },
            { type: "text", keyName: "delivery_card_1_title", title: "Картка 1: заголовок" },
            { type: "textarea", keyName: "delivery_card_1_text", title: "Картка 1: текст", rows: 3 },
            { type: "text", keyName: "delivery_card_2_badge", title: "Картка 2: badge" },
            { type: "text", keyName: "delivery_card_2_title", title: "Картка 2: заголовок" },
            { type: "textarea", keyName: "delivery_card_2_text", title: "Картка 2: текст", rows: 3 },
            { type: "text", keyName: "delivery_card_3_badge", title: "Картка 3: badge" },
            { type: "text", keyName: "delivery_card_3_title", title: "Картка 3: заголовок" },
            { type: "textarea", keyName: "delivery_card_3_text", title: "Картка 3: текст", rows: 3 },
            { type: "text", keyName: "delivery_card_4_badge", title: "Картка 4: badge" },
            { type: "text", keyName: "delivery_card_4_title", title: "Картка 4: заголовок" },
            { type: "textarea", keyName: "delivery_card_4_text", title: "Картка 4: текст", rows: 3 },
        ],
    },
    {
        title: "Сторінки: FAQ / Shipping / Returns",
        description: "Поширені питання, умови поставки та рекламації.",
        fields: [
            { type: "text", keyName: "faq_page_title", title: "FAQ: title" },
            { type: "textarea", keyName: "faq_page_subtitle", title: "FAQ: subtitle", rows: 2 },
            { type: "textarea", keyName: "faq_intro", title: "FAQ: вступ", rows: 3 },
            { type: "text", keyName: "faq_section_title", title: "FAQ: заголовок блоку" },
            { type: "text", keyName: "faq_question_1", title: "FAQ 1: питання" },
            { type: "textarea", keyName: "faq_answer_1", title: "FAQ 1: відповідь", rows: 3 },
            { type: "text", keyName: "faq_question_2", title: "FAQ 2: питання" },
            { type: "textarea", keyName: "faq_answer_2", title: "FAQ 2: відповідь", rows: 3 },
            { type: "text", keyName: "faq_question_3", title: "FAQ 3: питання" },
            { type: "textarea", keyName: "faq_answer_3", title: "FAQ 3: відповідь", rows: 3 },
            { type: "text", keyName: "faq_question_4", title: "FAQ 4: питання" },
            { type: "textarea", keyName: "faq_answer_4", title: "FAQ 4: відповідь", rows: 3 },
            { type: "text", keyName: "faq_question_5", title: "FAQ 5: питання" },
            { type: "textarea", keyName: "faq_answer_5", title: "FAQ 5: відповідь", rows: 3 },
            { type: "text", keyName: "faq_contact_title", title: "FAQ: заголовок контакту" },
            { type: "textarea", keyName: "faq_contact_text", title: "FAQ: текст контакту", rows: 3 },
            { type: "text", keyName: "shipping_page_title", title: "Shipping: title" },
            { type: "textarea", keyName: "shipping_page_subtitle", title: "Shipping: subtitle", rows: 2 },
            { type: "textarea", keyName: "shipping_intro", title: "Shipping: вступ", rows: 3 },
            { type: "text", keyName: "shipping_scenario_title", title: "Shipping: базовий сценарій" },
            { type: "textarea", keyName: "shipping_scenario_list", title: "Shipping: кроки", description: "Один рядок = один крок", rows: 5 },
            { type: "text", keyName: "shipping_timing_title", title: "Shipping: строки заголовок" },
            { type: "textarea", keyName: "shipping_timing_text_1", title: "Shipping: строки текст 1", rows: 2 },
            { type: "textarea", keyName: "shipping_timing_text_2", title: "Shipping: строки текст 2", rows: 2 },
            { type: "text", keyName: "returns_page_title", title: "Returns: title" },
            { type: "textarea", keyName: "returns_page_subtitle", title: "Returns: subtitle", rows: 2 },
            { type: "textarea", keyName: "returns_intro", title: "Returns: вступ", rows: 3 },
            { type: "text", keyName: "returns_requirements_title", title: "Returns: що потрібно" },
            { type: "textarea", keyName: "returns_requirements_list", title: "Returns: список", description: "Один рядок = один пункт", rows: 5 },
            { type: "text", keyName: "returns_process_title", title: "Returns: порядок роботи" },
            { type: "textarea", keyName: "returns_process_text_1", title: "Returns: текст 1", rows: 3 },
            { type: "textarea", keyName: "returns_process_text_2", title: "Returns: текст 2", rows: 2 },
        ],
    },
];
